name:  samplename

on: [push]

jobs:
  listing-files:
    runs-on: ubuntu-latest
    steps:
      - name: list-files
        run: |
          pwd
          ls -la
      - name: checkout
        uses: actions/checkout@v1
      - name: list-files after checkout
        run: |
          pwd
          ls -la
  run-shell-command:
    runs-on: ubuntu-latest
    steps: 
      - name: echo a string
        run: echo "Hello world"
      - name: multilinescript
        run: |
          java -version
          git --version
      -name: pythoncommand
        run:  |
          import platform
          print(platform.processor())
        shell: python
